query myPosts(
    $input: FindMyPostsRequest!
) {
    myPosts(input: $input) {
        data {
            id
            title
            description
            isLiked
            likesCount
            mediaUrl
            createdAt
            updatedAt
            deletedAt
            author {
                id
                firstName
                lastName
                middleName
                avatarUrl
            }
        }
        pageInfo{
            count
        }
    }
}

mutation myPostDelete($input: PostIdRequest!) {
    postDelete(input: $input) {
        ok
    }
}
